version: '3.8'
services:
  antink:
    build: .
    container_name: antink_container
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    volumes:
      - ./antink_mount:/mnt/antink_mount
      - ./it24_host:/mnt/original
      - ./antink-logs:/mnt/logs
    tty: true
